words_list=[["APPLE","BANANA","ORANGE","AVOCADO","STRAWBERRY","PINEAPPLE"],["GODZILLA","ROBIN HOOD","THE FAULT IN OUR STARS","SINGHAM","CONTAGION"],["DARK","NARUTO","FRIENDS","THE BIG BANG THEORY","BREAKING BAD","GAME OF THRONES"],["GOD OF WAR","HORIZON","ASSASSIN'S CREED","GRAND THEFT AUTO","CALL OF DUTY","PLAYER UNKNOWN BATTLEGROUND"]]
words_dict={
0:"Fruits",
1:"Movies",
2:"Series",
3:"Games"
}
