words_list=[["APRICOT","APPLE","BANANA","BLUEBERRY","CHERRY","COCONUT","DRAGONFRUIT","EGGPLANT","MULLBERRY","OLIVE","ORANGE","AVOCADO","STRAWBERRY","PINEAPPLE"],
            ["BLACK PANTHER","AVENGERS: ENDGAME","THE WIZARD OF OZ","WONDER WOMAN","A QUIET PLACE","GODZILLA","ROBIN HOOD","THE FAULT IN OUR STARS","SINGHAM","CONTAGION"],
            ["DARK","NARUTO","FRIENDS","THE BIG BANG THEORY","BREAKING BAD","GAME OF THRONES"],
            ["GOD OF WAR","HORIZON","ASSASSIN'S CREED","GRAND THEFT AUTO","CALL OF DUTY","PLAYER UNKNOWN BATTLEGROUND","VALORANT"]]
words_dict={
0:"Fruits",
1:"Movies",
2:"Series",
3:"Games"
}
