easy=[["APPLE","BANANA","ORANGE","MANGO","PEAR"],["IT","THE MEG","TROY","NOAH","ZODIAC"],["DARK","NARUTO","FRIENDS","BABIES","LUCIFER","GOTHAM"],["GOD OF WAR","HORIZON","ASSASSIN'S CREED","GTA","COD","PUBG"]]
medium=[["AVACADO","STRAWBERRY"],["THE ITALIAN JOB","THE GOLDEN COMPASS","THE MUMMY"],["THE WITCHER","WARRIOR NUN","INTO THE NIGHT","STRANGER THINGS"],["CALL OF DUTY","GRAND THEFT AUTO"]]
hard=[["POMEGRANATE","JACKFRUIT","DURIAN","FEIJOA"],["CASTLE ROCK","I","AXL","EL CHAPO"],["HEMLOCK GROVE","EL CHEMA"],["PLAYERUNKNOWN BATTLE GROUND"]]
words_dict={
0:"Fruits",
1:"Movies",
2:"Series",
3:"Games"
}
